baseurl = "/"
DefaultContentLanguage = "es"
#DefaultContentLanguage = "ja"
title = "R-para Microbios"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "microbiostats"
googleAnalytics = "UA-105146909-1"


[Params]
  subtitle = "R + Estadística + Ciencia + Microbios"
  logo = "img/density.png"
  favicon = "img/density.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Carlos Neftaly"
  website = "microbiostats.com"
  email = "neftalyl@microbiostats.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "carlosneftaly"
 # gitlab = "username"
  twitter = "neftalyl"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

#[[menu.main]]
  #  name = "Blog"
   # url = ""
   # weight = 1

[[menu.main]]
    name = "Acerca de mí"
    url = "page/about/"
    weight = 3


[[menu.main]]
    identifier = "DOE-MIA"
    name = "DOE-MIA"
    weight = 2
    
[[menu.main]]
    parent = "DOE-MIA"
    name = "Diapositivas"
    url = "page/diapo/"
    weight = 1



